/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import AWS from 'aws-sdk'

const awsConfig = {
   accessKeyId: 'AKIAXBPHHEJ344324J5J',
   secretAccessKey: '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',
   region: 'ap-southeast-1',
    
};
AWS.config.update(awsConfig);


export default AWS;
